# かんたん
Quiz.create(title: '「A」の音は？', content: "音名「A」の階名「ラ」です。", strings: ["６弦", "５弦", "４弦", "３弦"], frets: ["開放", "１フレット", "３フレット", "４フレット"], answer: "５弦開放", category: 1)
Quiz.create(title: '「A」の音は？', content: "音名「A」の階名「ラ」です。", strings: ["４弦", "３弦", "２弦", "１弦"], frets: ["開放", "１フレット", "２フレット", "３フレット"], answer: "３弦２フレット", category: 1)
Quiz.create(title: '「C」の音は？', content: "音名「C」の階名「ド」です。", strings: ["６弦", "５弦", "３弦", "１弦"], frets: ["４フレット", "３フレット", "２フレット", "１フレット"], answer: "５弦３フレット", category: 1)
Quiz.create(title: '「C」の音は？', content: "音名「C」の階名「ド」です。", strings: ["１弦", "２弦", "３弦", "４弦"], frets: ["１フレット", "２フレット", "３フレット", "４フレット"], answer: "２弦１フレット", category: 1)
Quiz.create(title: '「D」の音は？', content: "音名「D」の階名「レ」です。", strings: ["１弦", "２弦", "３弦", "４弦"], frets: ["４フレット", "３フレット", "２フレット", "１フレット"], answer: "２弦３フレット", category: 1)
Quiz.create(title: '「D」の音は？', content: "音名「D」の階名「レ」です。", strings: ["３弦", "４弦", "５弦", "６弦"], frets: ["１フレット", "２フレット", "３フレット", "開放"], answer: "４弦開放", category: 1)
Quiz.create(title: '「E」の音は？', content: "音名「E」の階名「ミ」です。", strings: ["５弦", "２弦", "３弦", "１弦"], frets: ["１フレット", "２フレット", "４フレット", "開放"], answer: "１弦開放", category: 1)
Quiz.create(title: '「E」の音は？', content: "音名「E」の階名「ミ」です。", strings: ["６弦", "４弦", "３弦", "２弦"], frets: ["１フレット", "２フレット", "４フレット", "開放"], answer: "６弦開放", category: 1)
Quiz.create(title: '「E」の音は？', content: "音名「E」の階名「ミ」です。", strings: ["１弦", "２弦", "３弦", "４弦"], frets: ["４フレット", "３フレット", "２フレット", "１フレット"], answer: "４弦２フレット", category: 1)
Quiz.create(title: '「B」の音は？', content: "音名「B」の階名「シ」です。", strings: ["１弦", "２弦", "４弦", "５弦"], frets: ["開放", "１フレット", "３フレット", "４フレット"], answer: "２弦開放", category: 1)
Quiz.create(title: '「B」の音は？', content: "音名「B」の階名「シ」です。", strings: ["１弦", "４弦", "５弦", "６弦"], frets: ["１フレット", "２フレット", "３フレット", "開放"], answer: "５弦２フレット", category: 1)
Quiz.create(title: '「B」の音は？', content: "音名「B」の階名「シ」です。", strings: ["１弦", "２弦", "３弦", "６弦"], frets: ["１フレット", "２フレット", "３フレット", "４フレット"], answer: "３弦４フレット", category: 1)
Quiz.create(title: '「G」の音は？', content: "音名「G」の階名「ソ」です。", strings: ["６弦", "５弦", "４弦", "３弦"], frets: ["４フレット", "３フレット", "２フレット", "１フレット"], answer: "６弦３フレット", category: 1)
Quiz.create(title: '「G」の音は？', content: "音名「G」の階名「ソ」です。", strings: ["１弦", "２弦", "３弦", "４弦"], frets: ["開放", "１フレット", "２フレット", "４フレット"], answer: "３弦開放", category: 1)
Quiz.create(title: '「G」の音は？', content: "音名「G」の階名「ソ」です。", strings: ["５弦", "４弦", "２弦", "１弦"], frets: ["４フレット", "３フレット", "２フレット", "１フレット"], answer: "１弦３フレット", category: 1)
Quiz.create(title: '「F」の音は？', content: "音名「F」の階名「ファ」です。", strings: ["６弦", "５弦", "４弦", "３弦"], frets: ["４フレット", "開放", "２フレット", "１フレット"], answer: "６弦１フレット", category: 1)
Quiz.create(title: '「F」の音は？', content: "音名「F」の階名「ファ」です。", strings: ["１弦", "２弦", "３弦", "４弦"], frets: ["４フレット", "開放", "３フレット", "２フレット"], answer: "４弦３フレット", category: 1)
Quiz.create(title: '「F」の音は？', content: "音名「F」の階名「ファ」です。", strings: ["５弦", "３弦", "２弦", "１弦"], frets: ["１フレット", "３フレット", "開放", "２フレット"], answer: "１弦１フレット", category: 1)
# # ふつう
# Quiz.create(title: '「F#」の音は？', content: "音名「F#」の階名「ファ#」です。", options: ["６弦２フレット", "４弦３フレット", "３弦２フレット", "１弦１フレット"], answer: 0, category: 2)
# # むずかしい
# Quiz.create(title: '「F」の音は？', content: "音名「F」の階名「ファ」です。", options: ["５弦７フレット", "４弦９フレット", "３弦１０フレット", "２弦１２フレット"], answer: 0, category: 3)